name: Update Readme with Activity Graph

on:
  schedule:
    - cron: '*/8 * * * *'
  workflow_dispatch:

jobs:
  update-readme-graph:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Generate activity graph
        uses: theactionhero/github-readme-activity-graph@v1.4.6
        with:
          user_name: ${{ github.repository_owner }}
          theme: react-dark 
          show_title: true
          title: "Wilhen's github activity graph"
          commit_message: '[bot] Actualizar gráfico de actividad'

      - name: Push activity-graph.svg
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.event.repository.owner.email || 'action@users.noreply.github.com' }}
          git add README.md
          git commit -m "Update activity graph" || exit 0
          git push
