name: Update Readme with Activity Graph

on:
  schedule:
    - cron: '*/8 * * * *'
  workflow_dispatch:

jobs:
  update-readme-graph:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          options: theme=react-dark&title=Wilhen's github activity graph
          output_path: dist/activity-graph.svg
          token: ${{ secrets.WF_README }}

      - name: Push activity-graph.svg
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.WF_README }}
